---
title: "ACM_Beginning_DS_Project"
author: "Khushi Chaudhari"
date: "2025-02-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Imports

```{r}
# uncomment the 2 lines below and run ONCE

install.packages("ggplot2")
install.packages("tidyverse")

# great package for visualizations
library(ggplot2)
# great package for data manipulation
library(tidyverse)
```
ggplot2 -> the package to visualize the data


```{r}
# imports the dataset into variable "df"
# update the path to match path of your local file

df <- read.csv("ACM Data Science Survey (Responses) - Form Responses 1.csv")

# prints out the first few lines of the dataset
head(df,5)
```

```{r}
# dataset fills empty slots with "", not NA.
#so when we test is.na, the sum is 0
sum (is.na(df))
sum(is.na(df$`What.is.your.primary.mode.of.transportation.`))

# count how many responses are missing in each column
sum(df == "")

sum(df$`What.is.your.primary.mode.of.transportation.` == "")
sum(df$`Do you live on campus(near-campus apartments or on campus apartments/dorms) or commute(living in a house off campus UCR)?` == "")
sum(df$`How far is your commute to campus? (0 (I live on campus), 1-5, 6-10, 11-20, 21+ miles)` == "")
sum(df$`How satisfied are you with the availability of parking, public transit, or other facilities on campus?` == "")
sum(df$`Do you feel your living situation affects your participation in campus activities?` == "")
sum(df$`How many on-campus organizations are you actively involved in (including attending meetings, participating in events)?` == "")
sum(df$`On a scale of 1-5, how fulfilled do you feel about your social life?` == "")
sum(df$`How many hours of sleep do you get on average?(write the numerical value Ex. 10 or 1 )` == "")
sum(df$`How many meals do you eat per day? (0, 1, 2, 3, 4, 5+)` == "")

# now we know there's one response missing in the column "What.is.your.primary.mode.of.transportation."
```
```{r}
#convert "" into NA
df[df == ""] <- NA

#test again
sum(df == "")

sum(df$`What.is.your.primary.mode.of.transportation.` == "")

```



